### PR TITLE
Opt cm 15.0 Stweks New Icons

### PR DESCRIPTION
**Pull request by DoggoOfSpeed**
[STweaks-opt-cm-15.0.zip](https://github.com/JDCTeam/STweaks/files/1510620/STweaks-opt-cm-15.0.zip)

### CODE REVIEW

**Comment by dkati** [comment]
@Vv2233Bb ?

**Comment by DoggoOfSpeed** [comment]
@dkati?

**Comment by dkati** [comment]
@Vv2233Bb i am using mobile device and i cant understand the pull request

**Comment by dkati** [comment]
@Vv2233Bb the problem is that i cant see the actual icons

**Comment by DoggoOfSpeed** [comment]
Maybe try to download the zip, unzip it and press the icon.

**Comment by dkati** [comment]
Thanks for that mate
!

**Comment by DoggoOfSpeed** [comment]
Hopefully this will look like from 2017😀

**Pull request merged**
